"""Схема портала одной миграцией: семнадцать таблиц, индексы, ограничения.

Девятнадцать миграций Ф14-Ф15 схлопнуты сюда, когда база ещё не была в
проде. Не `squashmigrations`: две миграции с `RunPython` стоят барьером
для оптимизатора, и схлопнутая версия продолжала бы заводить
`Story.chapters`, `Tag.usage_count`, `LibraryEntry.progress_chapter` с
их индексами, чтобы следующей операцией удалить (DEC-51, DEC-52, DEC-53).
История ходов лежит в git и в реестре решений; схеме от неё ничего не
нужно.

`pg_trgm` создаётся здесь же, до триграммных индексов: поиск ищет
подстроку (`ILIKE '%жағалау%'`), а её не берёт ни один B-tree —
подстрока начинается не с начала строки, и Postgres читает таблицу
целиком. Триграммы берут её с любой позиции и складывают регистр сами,
так что «РЫСҚАЛИ» и «рысқали» идут одним путём. Полнотекстового поиска
здесь намеренно нет: `SearchVector` ищет словами, и «Жағал» перестало бы
находить «Жағалау» — это смена поведения продукта, а не оптимизация.
Расширение доверенное с Postgres 13 и суперпользователя не требует.
"""

# Generated by Django 6.0.5 on 2026-08-29 07:14

import core.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='BlockedTagPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=48, unique=True, verbose_name='үлгі')),
                ('note', models.CharField(blank=True, max_length=120, verbose_name='түсініктеме')),
            ],
            options={
                'verbose_name': 'тыйым салынған үлгі',
                'verbose_name_plural': 'тыйым салынған үлгілер',
                'ordering': ('pattern',),
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='нөмірі')),
                ('title', models.CharField(max_length=120, verbose_name='атауы')),
                ('body', models.TextField(blank=True, verbose_name='мәтіні')),
                ('char_count', models.PositiveIntegerField(default=0, verbose_name='таңба саны')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='жасалған')),
            ],
            options={
                'verbose_name': 'бөлім',
                'verbose_name_plural': 'бөлімдер',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=120, verbose_name='атауы')),
                ('tint_hue', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(360)], verbose_name='түс (OKLCH hue)')),
                ('icon', models.CharField(max_length=32, verbose_name='иконка')),
                ('curator', models.CharField(default='редакция', max_length=80, verbose_name='құрастырған')),
                ('description', models.TextField(blank=True, verbose_name='сипаттамасы')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='реті')),
            ],
            options={
                'verbose_name': 'жинақ',
                'verbose_name_plural': 'жинақтар',
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=40, verbose_name='атауы')),
                ('hue', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(360)], verbose_name='түс (OKLCH hue)')),
                ('icon', models.CharField(blank=True, max_length=32, verbose_name='иконка')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='реті')),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанрлар',
                'ordering': ('position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SchoolLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=32, verbose_name='арна')),
                ('title', models.CharField(max_length=120, verbose_name='атауы')),
                ('subtitle', models.CharField(blank=True, max_length=120, verbose_name='мазмұны')),
                ('url', models.URLField(verbose_name='сілтеме')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='реті')),
            ],
            options={
                'verbose_name': 'мектеп сілтемесі',
                'verbose_name_plural': 'мектеп сілтемелері',
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='нақты аты')),
                ('pen_name', models.CharField(blank=True, max_length=60, verbose_name='лақап аты')),
                ('bio', models.CharField(blank=True, max_length=200, verbose_name='өзі туралы')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='жасы')),
                ('gender', models.CharField(blank=True, choices=[('boy', 'Ұл'), ('girl', 'Қыз')], max_length=4, verbose_name='жынысы')),
                ('avatar', models.FileField(blank=True, max_length=200, upload_to=core.models.user_avatar_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'], message='Тек растр сурет: png, jpg, webp. SVG қабылданбайды (BR-46).')], verbose_name='аватар')),
                ('followers', models.PositiveIntegerField(default=0, verbose_name='оқырман саны')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пайдаланушы',
                'verbose_name_plural': 'пайдаланушылар',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChapterPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='сұрақ')),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='core.chapter', verbose_name='бөлім')),
            ],
            options={
                'verbose_name': 'бөлім сауалнамасы',
                'verbose_name_plural': 'бөлім сауалнамалары',
            },
        ),
        migrations.CreateModel(
            name='ChapterReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('kuldim', 'Күлдім'), ('jyladym', 'Жыладым'), ('juregim', 'Жүрегім'), ('shabyt', 'Шабыт'), ('tangaldym', 'Таңғалдым')], max_length=16, verbose_name='реакция')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='саны')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.chapter', verbose_name='бөлім')),
            ],
            options={
                'verbose_name': 'бөлім реакциясы',
                'verbose_name_plural': 'бөлім реакциялары',
                'ordering': ('kind',),
            },
        ),
        migrations.CreateModel(
            name='ChapterReactionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('kuldim', 'Күлдім'), ('jyladym', 'Жыладым'), ('juregim', 'Жүрегім'), ('shabyt', 'Шабыт'), ('tangaldym', 'Таңғалдым')], max_length=16, verbose_name='реакция')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='басылған')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_votes', to='core.chapter', verbose_name='бөлім')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_reaction_votes', to=settings.AUTH_USER_MODEL, verbose_name='оқырман')),
            ],
            options={
                'verbose_name': 'бөлім реакциясының дауысы',
                'verbose_name_plural': 'бөлім реакцияларының дауыстары',
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=120, verbose_name='атауы')),
                ('subtitle', models.CharField(blank=True, max_length=160, verbose_name='санаты')),
                ('opens_on', models.DateField(verbose_name='қабылдау басталады')),
                ('closes_on', models.DateField(verbose_name='қабылдау жабылады')),
                ('results_on', models.DateField(verbose_name='қорытынды жарияланады')),
                ('prize_kzt', models.PositiveIntegerField(blank=True, null=True, verbose_name='сыйлық (₸)')),
                ('poster', models.FileField(blank=True, max_length=200, upload_to=core.models.contest_poster_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'], message='Тек растр сурет: png, jpg, webp. SVG қабылданбайды (BR-46).')], verbose_name='афиша')),
                ('series', models.SlugField(blank=True, max_length=64, verbose_name='серия')),
                ('description', models.TextField(blank=True, verbose_name='сипаттамасы')),
                ('min_chars', models.PositiveIntegerField(default=5000, verbose_name='ең аз көлемі')),
                ('max_chars', models.PositiveIntegerField(default=15000, verbose_name='ең көп көлемі')),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ең кіші жас')),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ең үлкен жас')),
            ],
            options={
                'verbose_name': 'байқау',
                'verbose_name_plural': 'байқаулар',
                'ordering': ('-results_on',),
                'constraints': [models.CheckConstraint(condition=models.Q(('opens_on__lte', models.F('closes_on'))), name='contest_opens_before_it_closes'), models.CheckConstraint(condition=models.Q(('closes_on__lt', models.F('results_on'))), name='contest_results_after_it_closes')],
            },
        ),
        migrations.CreateModel(
            name='ContestAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=48, verbose_name='slug')),
                ('title', models.CharField(max_length=80, verbose_name='атауы')),
                ('image', models.FileField(blank=True, max_length=200, upload_to=core.models.award_image_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'], message='Тек растр сурет: png, jpg, webp. SVG қабылданбайды (BR-46).')], verbose_name='эмблема')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='сипаттамасы')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='реті')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_set', to='core.contest', verbose_name='байқау')),
            ],
            options={
                'verbose_name': 'байқау номинациясы',
                'verbose_name_plural': 'байқау номинациялары',
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ContestCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='шарт')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='реті')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_set', to='core.contest', verbose_name='байқау')),
            ],
            options={
                'verbose_name': 'байқау шарты',
                'verbose_name_plural': 'байқау шарттары',
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='жазылған күні')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to=settings.AUTH_USER_MODEL, verbose_name='кім жазылды')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_set', to=settings.AUTH_USER_MODEL, verbose_name='кімге жазылды')),
            ],
            options={
                'verbose_name': 'жазылым',
                'verbose_name_plural': 'жазылымдар',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='JuryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='аты-жөні')),
                ('role', models.CharField(max_length=40, verbose_name='рөлі')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='реті')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_set', to='core.contest', verbose_name='байқау')),
            ],
            options={
                'verbose_name': 'қазылар алқасының мүшесі',
                'verbose_name_plural': 'қазылар алқасы',
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, verbose_name='slug')),
                ('text', models.CharField(max_length=160, verbose_name='мәтіні')),
                ('votes', models.PositiveIntegerField(default=0, verbose_name='дауыс')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='реті')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_set', to='core.chapterpoll', verbose_name='сауалнама')),
            ],
            options={
                'verbose_name': 'сауалнама нұсқасы',
                'verbose_name_plural': 'сауалнама нұсқалары',
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дауыс берген')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_set', to='core.polloption', verbose_name='нұсқа')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_set', to='core.chapterpoll', verbose_name='сауалнама')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL, verbose_name='оқырман')),
            ],
            options={
                'verbose_name': 'сауалнама дауысы',
                'verbose_name_plural': 'сауалнама дауыстары',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=120, verbose_name='атауы')),
                ('cover', models.FileField(blank=True, max_length=200, upload_to=core.models.story_cover_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'], message='Тек растр сурет: png, jpg, webp. SVG қабылданбайды (BR-46).')], verbose_name='мұқаба')),
                ('annotation', models.TextField(blank=True, verbose_name='аннотация')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('NotPublished', 'NotPublished'), ('OnProcess', 'OnProcess'), ('Completed', 'Completed'), ('OnModeration', 'OnModeration')], default='NotPublished', max_length=16, verbose_name='мәртебесі')),
                ('audience', models.CharField(blank=True, max_length=8, verbose_name='жас белгісі')),
                ('format', models.CharField(choices=[('single', 'single'), ('serial', 'serial')], default='serial', max_length=8, verbose_name='түрі')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='оқылым')),
                ('recent_views', models.PositiveIntegerField(default=0, verbose_name='14 күндегі оқылым')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='лайк')),
                ('comments', models.PositiveIntegerField(default=0, verbose_name='пікір')),
                ('is_editorial_pick', models.BooleanField(default=False, verbose_name='редакция таңдауы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='жасалған')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='өзгертілген')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL, verbose_name='авторы')),
                ('primary_genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_stories', to='core.genre', verbose_name='негізгі жанр')),
                ('secondary_genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_stories', to='core.genre', verbose_name='қосымша жанр')),
            ],
            options={
                'verbose_name': 'шығарма',
                'verbose_name_plural': 'шығармалар',
                'ordering': ('-recent_views', 'title'),
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_chapter', models.PositiveSmallIntegerField(default=1, verbose_name='бөлім')),
                ('quote', models.TextField(blank=True, verbose_name='соңғы абзац')),
                ('minutes_left', models.PositiveSmallIntegerField(default=0, verbose_name='қалған минут')),
                ('last_read_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='соңғы оқыған күні')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL, verbose_name='оқырман')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='core.story', verbose_name='шығарма')),
            ],
            options={
                'verbose_name': 'оқу барысы',
                'verbose_name_plural': 'оқу барысы',
                'ordering': ('-last_read_on',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('comment', 'comment'), ('like', 'like'), ('new_chapter', 'new_chapter'), ('follower', 'follower'), ('moderation', 'moderation'), ('contest', 'contest')], max_length=16, verbose_name='түрі')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='болған уақыты')),
                ('outcome', models.CharField(blank=True, choices=[('approved', 'Жарияланды'), ('needs_work', 'Толықтыру қажет'), ('rejected', 'Қабылданбады')], max_length=16, verbose_name='модерация нәтижесі')),
                ('text', models.CharField(blank=True, max_length=300, verbose_name='оқиға')),
                ('read', models.BooleanField(default=False, verbose_name='оқылды')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caused_notifications', to=settings.AUTH_USER_MODEL, verbose_name='кім')),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.contest', verbose_name='байқау')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='кімге')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.story', verbose_name='шығарма')),
            ],
            options={
                'verbose_name': 'хабарлама',
                'verbose_name_plural': 'хабарламалар',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LibraryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('saved', 'saved'), ('reading', 'reading'), ('done', 'done')], max_length=16, verbose_name='түрі')),
                ('added_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='қосылған күні')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library', to=settings.AUTH_USER_MODEL, verbose_name='оқырман')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_entries', to='core.story', verbose_name='шығарма')),
            ],
            options={
                'verbose_name': 'кітапхана жазбасы',
                'verbose_name_plural': 'кітапхана жазбалары',
                'ordering': ('-added_on', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='реті')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_set', to='core.collection', verbose_name='жинақ')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='core.story', verbose_name='шығарма')),
            ],
            options={
                'verbose_name': 'жинақтағы шығарма',
                'verbose_name_plural': 'жинақтағы шығармалар',
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.story', verbose_name='шығарма'),
        ),
        migrations.CreateModel(
            name='BookOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editorial_note', models.TextField(verbose_name='редакциядан')),
                ('quote', models.TextField(verbose_name='үзінді')),
                ('published_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='апта басы')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='core.story', verbose_name='шығарма')),
            ],
            options={
                'verbose_name': 'аптаның кітабы',
                'verbose_name_plural': 'аптаның кітаптары',
                'ordering': ('-published_on',),
                'get_latest_by': 'published_on',
            },
        ),
        migrations.CreateModel(
            name='AwardGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='түсініктеме')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_set', to='core.contest', verbose_name='байқау')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_set', to='core.contestaward', verbose_name='номинация')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_grants', to='core.story', verbose_name='шығарма')),
            ],
            options={
                'verbose_name': 'марапат',
                'verbose_name_plural': 'марапаттар',
                'ordering': ('award__position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='StoryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='бөлім')),
                ('text', models.TextField(verbose_name='мәтіні')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='ұнату')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='жазылған')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='авторы')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_set', to='core.storycomment', verbose_name='жауап')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='core.story', verbose_name='шығарма')),
            ],
            options={
                'verbose_name': 'пікір',
                'verbose_name_plural': 'пікірлер',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='басылған')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='оқырман')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_set', to='core.storycomment', verbose_name='пікір')),
            ],
            options={
                'verbose_name': 'пікір ұнатуы',
                'verbose_name_plural': 'пікір ұнатулары',
            },
        ),
        migrations.CreateModel(
            name='StoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='оқылған сәт')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_set', to='core.story', verbose_name='шығарма')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='оқырман')),
            ],
            options={
                'verbose_name': 'оқылым',
                'verbose_name_plural': 'оқылымдар',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_on', models.DateField(verbose_name='берілген күні')),
                ('status', models.CharField(choices=[('reviewing', 'reviewing'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='reviewing', max_length=16, verbose_name='күйі')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='қазылар пікірі')),
                ('ai_declaration', models.CharField(choices=[('no', 'no'), ('partial', 'partial'), ('yes', 'yes')], default='no', max_length=8, verbose_name='AI көмегі')),
                ('age_confirmed', models.BooleanField(default=False, verbose_name='жасын растады')),
                ('rules_confirmed', models.BooleanField(default=False, verbose_name='ережені растады')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='авторы')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_set', to='core.contest', verbose_name='байқау')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.story', verbose_name='шығарма')),
            ],
            options={
                'verbose_name': 'өтінім',
                'verbose_name_plural': 'өтінімдер',
                'ordering': ('-submitted_on',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, max_length=48, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=48, verbose_name='атауы')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=16, verbose_name='күйі')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='жасалған')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'тегтер',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['status'], name='core_tag_status_6e19bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='қосылған')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.story', verbose_name='шығарма')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tag', verbose_name='тег')),
            ],
            options={
                'verbose_name': 'жұмыс тегі',
                'verbose_name_plural': 'жұмыс тегтері',
            },
        ),
        migrations.AddField(
            model_name='story',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='stories', through='core.StoryTag', to='core.tag', verbose_name='тегтер'),
        ),
        migrations.CreateModel(
            name='TimelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80, verbose_name='атауы')),
                ('starts', models.DateField(verbose_name='басталуы')),
                ('ends', models.DateField(verbose_name='аяқталуы')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='реті')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_set', to='core.contest', verbose_name='байқау')),
            ],
            options={
                'verbose_name': 'байқау кезеңі',
                'verbose_name_plural': 'байқау кезеңдері',
                'ordering': ('position', 'starts'),
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['pen_name'], name='user_pen_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['username'], name='user_username_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='user_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='chapterreaction',
            constraint=models.UniqueConstraint(fields=('chapter', 'kind'), name='unique_reaction_kind_per_chapter'),
        ),
        migrations.AddConstraint(
            model_name='chapterreactionvote',
            constraint=models.UniqueConstraint(fields=('user', 'chapter'), name='one_reaction_per_user_per_chapter'),
        ),
        migrations.AddConstraint(
            model_name='contestaward',
            constraint=models.UniqueConstraint(fields=('contest', 'slug'), name='unique_award_slug_per_contest'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('follower', 'following'), name='unique_follow_pair'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(condition=models.Q(('follower', models.F('following')), _negated=True), name='no_self_follow'),
        ),
        migrations.AddConstraint(
            model_name='polloption',
            constraint=models.UniqueConstraint(fields=('poll', 'slug'), name='unique_option_slug_per_poll'),
        ),
        migrations.AddConstraint(
            model_name='pollvote',
            constraint=models.UniqueConstraint(fields=('user', 'poll'), name='one_vote_per_user_per_poll'),
        ),
        migrations.AddConstraint(
            model_name='readingprogress',
            constraint=models.UniqueConstraint(fields=('user', 'story'), name='one_progress_per_story'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='core_notifi_user_id_1cc5b6_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryentry',
            index=models.Index(fields=['user', 'kind'], name='core_librar_user_id_326c26_idx'),
        ),
        migrations.AddConstraint(
            model_name='libraryentry',
            constraint=models.UniqueConstraint(fields=('user', 'story'), name='one_library_entry_per_story'),
        ),
        migrations.AddConstraint(
            model_name='collectionitem',
            constraint=models.UniqueConstraint(fields=('collection', 'story'), name='unique_story_per_collection'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('story', 'number'), name='unique_chapter_number_per_story'),
        ),
        migrations.AddConstraint(
            model_name='awardgrant',
            constraint=models.UniqueConstraint(fields=('contest', 'award'), name='unique_grant_per_award'),
        ),
        migrations.AddConstraint(
            model_name='commentlike',
            constraint=models.UniqueConstraint(fields=('user', 'comment'), name='unique_like_per_user_per_comment'),
        ),
        migrations.AddIndex(
            model_name='storyview',
            index=models.Index(fields=['story', '-created_at'], name='core_storyv_story_i_870e74_idx'),
        ),
        migrations.AddIndex(
            model_name='storyview',
            index=models.Index(fields=['created_at'], name='core_storyv_created_70219a_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('contest', 'author'), name='one_submission_per_author_per_contest'),
        ),
        migrations.AddConstraint(
            model_name='storytag',
            constraint=models.UniqueConstraint(fields=('story', 'tag'), name='unique_tag_per_story'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['status'], name='core_story_status_023cb4_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['-recent_views'], name='core_story_recent__337c27_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['-views'], name='core_story_views_eaacf4_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['-created_at'], name='core_story_created_f3a776_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='story_title_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
