# Generated by Django 6.0.5 on 2026-08-23 07:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedTagPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=48, unique=True, verbose_name='үлгі')),
                ('note', models.CharField(blank=True, max_length=120, verbose_name='түсініктеме')),
            ],
            options={
                'verbose_name': 'тыйым салынған үлгі',
                'verbose_name_plural': 'тыйым салынған үлгілер',
                'ordering': ('pattern',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=40, verbose_name='атауы')),
                ('hue', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(360)], verbose_name='түс (OKLCH hue)')),
                ('icon', models.CharField(blank=True, max_length=32, verbose_name='иконка')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='реті')),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанрлар',
                'ordering': ('position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, max_length=48, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=48, verbose_name='атауы')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=16, verbose_name='күйі')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='жасалған')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'тегтер',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='нақты аты')),
                ('pen_name', models.CharField(blank=True, max_length=60, verbose_name='лақап аты')),
                ('bio', models.CharField(blank=True, max_length=200, verbose_name='өзі туралы')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пайдаланушы',
                'verbose_name_plural': 'пайдаланушылар',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
