# Generated by Django 6.0.5 on 2026-08-23 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reference_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=120, verbose_name='атауы')),
                ('cover', models.CharField(blank=True, max_length=200, verbose_name='мұқаба')),
                ('annotation', models.TextField(blank=True, verbose_name='аннотация')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('NotPublished', 'NotPublished'), ('OnProcess', 'OnProcess'), ('Completed', 'Completed'), ('OnModeration', 'OnModeration')], default='NotPublished', max_length=16, verbose_name='мәртебесі')),
                ('audience', models.CharField(blank=True, max_length=8, verbose_name='жас белгісі')),
                ('format', models.CharField(choices=[('single', 'single'), ('serial', 'serial')], default='serial', max_length=8, verbose_name='түрі')),
                ('chapters', models.PositiveSmallIntegerField(default=0, verbose_name='бөлім саны')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='оқылым')),
                ('recent_views', models.PositiveIntegerField(default=0, verbose_name='14 күндегі оқылым')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='лайк')),
                ('comments', models.PositiveIntegerField(default=0, verbose_name='пікір')),
                ('is_editorial_pick', models.BooleanField(default=False, verbose_name='редакция таңдауы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='жасалған')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='өзгертілген')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL, verbose_name='авторы')),
                ('primary_genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_stories', to='core.genre', verbose_name='негізгі жанр')),
                ('secondary_genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_stories', to='core.genre', verbose_name='қосымша жанр')),
                ('tags', models.ManyToManyField(blank=True, related_name='stories', to='core.tag', verbose_name='тегтер')),
            ],
            options={
                'verbose_name': 'шығарма',
                'verbose_name_plural': 'шығармалар',
                'ordering': ('-recent_views', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='нөмірі')),
                ('title', models.CharField(max_length=120, verbose_name='атауы')),
                ('body', models.TextField(blank=True, verbose_name='мәтіні')),
                ('char_count', models.PositiveIntegerField(default=0, verbose_name='таңба саны')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='жасалған')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.story', verbose_name='шығарма')),
            ],
            options={
                'verbose_name': 'бөлім',
                'verbose_name_plural': 'бөлімдер',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='ChapterReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('kuldim', 'Күлдім'), ('jyladym', 'Жыладым'), ('juregim', 'Жүрегім'), ('shabyt', 'Шабыт'), ('tangaldym', 'Таңғалдым')], max_length=16, verbose_name='реакция')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='саны')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.chapter', verbose_name='бөлім')),
            ],
            options={
                'verbose_name': 'бөлім реакциясы',
                'verbose_name_plural': 'бөлім реакциялары',
                'ordering': ('kind',),
                'constraints': [models.UniqueConstraint(fields=('chapter', 'kind'), name='unique_reaction_kind_per_chapter')],
            },
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['status'], name='core_story_status_023cb4_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['-recent_views'], name='core_story_recent__337c27_idx'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('story', 'number'), name='unique_chapter_number_per_story'),
        ),
    ]
