# Generated by Django 6.0.5 on 2026-09-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reference_data'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='contest',
            name='contest_opens_before_it_closes',
            constraint=models.CheckConstraint(condition=models.Q(('opens_on__lte', models.F('closes_on'))), name='contest_opens_before_it_closes', violation_error_message='Қабылдау басталмай тұрып жабыла алмайды.'),
        ),
        migrations.AlterConstraint(
            model_name='contest',
            name='contest_results_after_it_closes',
            constraint=models.CheckConstraint(condition=models.Q(('closes_on__lt', models.F('results_on'))), name='contest_results_after_it_closes', violation_error_message='Қорытынды қабылдау жабылғаннан кейін ғана жарияланады.'),
        ),
    ]
