# Generated by Django 6.0.5 on 2026-09-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reference_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.PositiveIntegerField(default=0, verbose_name='жазылушы саны'),
        ),
    ]
