# Generated by Django 6.0.5 on 2026-09-05 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='completed_by_author',
            field=models.BooleanField(default=False, verbose_name='аяқталды деп белгіленген'),
        ),
        migrations.CreateModel(
            name='ChapterRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='атауы')),
                ('body', models.TextField(blank=True, verbose_name='мәтіні')),
                ('char_count', models.PositiveIntegerField(default=0, verbose_name='таңба саны')),
                ('state', models.CharField(choices=[('draft', 'draft'), ('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='draft', max_length=16, verbose_name='күйі')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='жасалған')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='жіберілген')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='шешілген')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.chapter', verbose_name='бөлім')),
            ],
            options={
                'verbose_name': 'бөлім нұсқасы',
                'verbose_name_plural': 'бөлім нұсқалары',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='published_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.chapterrevision', verbose_name='жарияланған нұсқа'),
        ),
        migrations.AddIndex(
            model_name='chapterrevision',
            index=models.Index(fields=['state', 'submitted_at'], name='core_chapte_state_a13b38_idx'),
        ),
    ]
