# Generated by Django 6.0.5 on 2026-08-23 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_story_chapter_chapterreaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=120, verbose_name='атауы')),
                ('subtitle', models.CharField(blank=True, max_length=160, verbose_name='санаты')),
                ('opens_on', models.DateField(verbose_name='қабылдау басталады')),
                ('closes_on', models.DateField(verbose_name='қабылдау жабылады')),
                ('results_on', models.DateField(verbose_name='қорытынды жарияланады')),
                ('prize_kzt', models.PositiveIntegerField(blank=True, null=True, verbose_name='сыйлық (₸)')),
                ('poster', models.CharField(blank=True, max_length=200, verbose_name='афиша')),
                ('series', models.SlugField(blank=True, max_length=64, verbose_name='серия')),
                ('description', models.TextField(blank=True, verbose_name='сипаттамасы')),
                ('min_chars', models.PositiveIntegerField(default=5000, verbose_name='ең аз көлемі')),
                ('max_chars', models.PositiveIntegerField(default=15000, verbose_name='ең көп көлемі')),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ең кіші жас')),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ең үлкен жас')),
            ],
            options={
                'verbose_name': 'байқау',
                'verbose_name_plural': 'байқаулар',
                'ordering': ('-results_on',),
                'constraints': [models.CheckConstraint(condition=models.Q(('opens_on__lte', models.F('closes_on'))), name='contest_opens_before_it_closes'), models.CheckConstraint(condition=models.Q(('closes_on__lt', models.F('results_on'))), name='contest_results_after_it_closes')],
            },
        ),
        migrations.CreateModel(
            name='ContestAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=48, verbose_name='slug')),
                ('title', models.CharField(max_length=80, verbose_name='атауы')),
                ('image', models.CharField(blank=True, max_length=200, verbose_name='эмблема')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='сипаттамасы')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='реті')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_set', to='core.contest', verbose_name='байқау')),
            ],
            options={
                'verbose_name': 'байқау номинациясы',
                'verbose_name_plural': 'байқау номинациялары',
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='AwardGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='түсініктеме')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_grants', to='core.story', verbose_name='шығарма')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_set', to='core.contest', verbose_name='байқау')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_set', to='core.contestaward', verbose_name='номинация')),
            ],
            options={
                'verbose_name': 'марапат',
                'verbose_name_plural': 'марапаттар',
                'ordering': ('award__position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ContestCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='шарт')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='реті')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_set', to='core.contest', verbose_name='байқау')),
            ],
            options={
                'verbose_name': 'байқау шарты',
                'verbose_name_plural': 'байқау шарттары',
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='JuryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='аты-жөні')),
                ('role', models.CharField(max_length=40, verbose_name='рөлі')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='реті')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_set', to='core.contest', verbose_name='байқау')),
            ],
            options={
                'verbose_name': 'қазылар алқасының мүшесі',
                'verbose_name_plural': 'қазылар алқасы',
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_on', models.DateField(verbose_name='берілген күні')),
                ('status', models.CharField(choices=[('reviewing', 'reviewing'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='reviewing', max_length=16, verbose_name='күйі')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='қазылар пікірі')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='авторы')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_set', to='core.contest', verbose_name='байқау')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.story', verbose_name='шығарма')),
            ],
            options={
                'verbose_name': 'өтінім',
                'verbose_name_plural': 'өтінімдер',
                'ordering': ('-submitted_on',),
            },
        ),
        migrations.CreateModel(
            name='TimelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80, verbose_name='атауы')),
                ('starts', models.DateField(verbose_name='басталуы')),
                ('ends', models.DateField(verbose_name='аяқталуы')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='реті')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_set', to='core.contest', verbose_name='байқау')),
            ],
            options={
                'verbose_name': 'байқау кезеңі',
                'verbose_name_plural': 'байқау кезеңдері',
                'ordering': ('position', 'starts'),
            },
        ),
        migrations.AddConstraint(
            model_name='contestaward',
            constraint=models.UniqueConstraint(fields=('contest', 'slug'), name='unique_award_slug_per_contest'),
        ),
        migrations.AddConstraint(
            model_name='awardgrant',
            constraint=models.UniqueConstraint(fields=('contest', 'award'), name='unique_grant_per_award'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('contest', 'author'), name='one_submission_per_author_per_contest'),
        ),
    ]
