# Generated by Django 6.0.5 on 2026-09-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contest_date_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterrevision',
            name='state',
            field=models.CharField(choices=[('draft', 'Жоба'), ('pending', 'Модерацияда'), ('approved', 'Жарияланды'), ('rejected', 'Қабылданбады')], default='draft', max_length=16, verbose_name='күйі'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('comment', 'Пікір'), ('like', 'Реакция'), ('new_chapter', 'Жаңа бөлім'), ('follower', 'Жазылушы'), ('moderation', 'Модерация'), ('contest', 'Байқау'), ('tag', 'Тег')], max_length=16, verbose_name='түрі'),
        ),
        migrations.AlterField(
            model_name='story',
            name='format',
            field=models.CharField(choices=[('single', 'Бір бөлімді'), ('serial', 'Көп бөлімді')], default='serial', max_length=8, verbose_name='түрі'),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('Published', 'Жарияланды'), ('NotPublished', 'Жоба'), ('NeedsWork', 'Толықтыру қажет'), ('OnProcess', 'Жазылып жатыр'), ('Completed', 'Аяқталды'), ('OnModeration', 'Модерацияда')], default='NotPublished', max_length=16, verbose_name='мәртебесі'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='ai_declaration',
            field=models.CharField(choices=[('no', 'Жоқ'), ('partial', 'Жартылай'), ('yes', 'Иә')], default='no', max_length=8, verbose_name='AI көмегі'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('reviewing', 'Қаралуда'), ('accepted', 'Қабылданды'), ('rejected', 'Қабылданбады')], default='reviewing', max_length=16, verbose_name='күйі'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='status',
            field=models.CharField(choices=[('pending', 'Тексеруде'), ('accepted', 'Қабылданды'), ('rejected', 'Қабылданбады')], default='pending', max_length=16, verbose_name='күйі'),
        ),
    ]
