# Generated by Django 6.0.5 on 2026-09-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_status_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='resolution',
            field=models.CharField(blank=True, max_length=300, verbose_name='шешім себебі'),
        ),
    ]
