# Generated by Django 6.0.5 on 2026-08-23 08:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contest_contestaward_awardgrant_contestcondition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=120, verbose_name='атауы')),
                ('tint_hue', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(360)], verbose_name='түс (OKLCH hue)')),
                ('icon', models.CharField(max_length=32, verbose_name='иконка')),
                ('curator', models.CharField(default='редакция', max_length=80, verbose_name='құрастырған')),
                ('description', models.TextField(blank=True, verbose_name='сипаттамасы')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='реті')),
            ],
            options={
                'verbose_name': 'жинақ',
                'verbose_name_plural': 'жинақтар',
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SchoolLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=32, verbose_name='арна')),
                ('title', models.CharField(max_length=120, verbose_name='атауы')),
                ('subtitle', models.CharField(blank=True, max_length=120, verbose_name='мазмұны')),
                ('url', models.URLField(verbose_name='сілтеме')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='реті')),
            ],
            options={
                'verbose_name': 'мектеп сілтемесі',
                'verbose_name_plural': 'мектеп сілтемелері',
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.PositiveIntegerField(default=0, verbose_name='оқырман саны'),
        ),
        migrations.CreateModel(
            name='BookOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editorial_note', models.TextField(verbose_name='редакциядан')),
                ('quote', models.TextField(verbose_name='үзінді')),
                ('published_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='апта басы')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='core.story', verbose_name='шығарма')),
            ],
            options={
                'verbose_name': 'аптаның кітабы',
                'verbose_name_plural': 'аптаның кітаптары',
                'ordering': ('-published_on',),
                'get_latest_by': 'published_on',
            },
        ),
        migrations.CreateModel(
            name='ChapterPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='сұрақ')),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='core.chapter', verbose_name='бөлім')),
            ],
            options={
                'verbose_name': 'бөлім сауалнамасы',
                'verbose_name_plural': 'бөлім сауалнамалары',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('comment', 'comment'), ('like', 'like'), ('new_chapter', 'new_chapter'), ('follower', 'follower'), ('moderation', 'moderation'), ('contest', 'contest')], max_length=16, verbose_name='түрі')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='болған уақыты')),
                ('outcome', models.CharField(blank=True, choices=[('approved', 'Жарияланды'), ('needs_work', 'Толықтыру қажет'), ('rejected', 'Қабылданбады')], max_length=16, verbose_name='модерация нәтижесі')),
                ('text', models.CharField(blank=True, max_length=300, verbose_name='оқиға')),
                ('read', models.BooleanField(default=False, verbose_name='оқылды')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caused_notifications', to=settings.AUTH_USER_MODEL, verbose_name='кім')),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.contest', verbose_name='байқау')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.story', verbose_name='шығарма')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='кімге')),
            ],
            options={
                'verbose_name': 'хабарлама',
                'verbose_name_plural': 'хабарламалар',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StoryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='бөлім')),
                ('text', models.TextField(verbose_name='мәтіні')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='ұнату')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='жазылған')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='авторы')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_set', to='core.storycomment', verbose_name='жауап')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='core.story', verbose_name='шығарма')),
            ],
            options={
                'verbose_name': 'пікір',
                'verbose_name_plural': 'пікірлер',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='реті')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_set', to='core.collection', verbose_name='жинақ')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='core.story', verbose_name='шығарма')),
            ],
            options={
                'verbose_name': 'жинақтағы шығарма',
                'verbose_name_plural': 'жинақтағы шығармалар',
                'ordering': ('position', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('collection', 'story'), name='unique_story_per_collection')],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='жазылған күні')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to=settings.AUTH_USER_MODEL, verbose_name='кім жазылды')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_set', to=settings.AUTH_USER_MODEL, verbose_name='кімге жазылды')),
            ],
            options={
                'verbose_name': 'жазылым',
                'verbose_name_plural': 'жазылымдар',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('follower', 'following'), name='unique_follow_pair'), models.CheckConstraint(condition=models.Q(('follower', models.F('following')), _negated=True), name='no_self_follow')],
            },
        ),
        migrations.CreateModel(
            name='LibraryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('saved', 'saved'), ('reading', 'reading'), ('done', 'done')], max_length=16, verbose_name='түрі')),
                ('added_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='қосылған күні')),
                ('progress_chapter', models.PositiveSmallIntegerField(default=1, verbose_name='бөлім')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_entries', to='core.story', verbose_name='шығарма')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library', to=settings.AUTH_USER_MODEL, verbose_name='оқырман')),
            ],
            options={
                'verbose_name': 'кітапхана жазбасы',
                'verbose_name_plural': 'кітапхана жазбалары',
                'ordering': ('-added_on', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('user', 'story'), name='one_library_entry_per_story')],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, verbose_name='slug')),
                ('text', models.CharField(max_length=160, verbose_name='мәтіні')),
                ('votes', models.PositiveIntegerField(default=0, verbose_name='дауыс')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='реті')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_set', to='core.chapterpoll', verbose_name='сауалнама')),
            ],
            options={
                'verbose_name': 'сауалнама нұсқасы',
                'verbose_name_plural': 'сауалнама нұсқалары',
                'ordering': ('position', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('poll', 'slug'), name='unique_option_slug_per_poll')],
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_chapter', models.PositiveSmallIntegerField(default=1, verbose_name='бөлім')),
                ('quote', models.TextField(blank=True, verbose_name='соңғы абзац')),
                ('minutes_left', models.PositiveSmallIntegerField(default=0, verbose_name='қалған минут')),
                ('last_read_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='соңғы оқыған күні')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='core.story', verbose_name='шығарма')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL, verbose_name='оқырман')),
            ],
            options={
                'verbose_name': 'оқу барысы',
                'verbose_name_plural': 'оқу барысы',
                'ordering': ('-last_read_on',),
                'constraints': [models.UniqueConstraint(fields=('user', 'story'), name='one_progress_per_story')],
            },
        ),
    ]
