# Generated by Django 6.0.5 on 2026-08-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_collection_schoollink_user_followers_bookofweek_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, verbose_name='қолданылған саны'),
        ),
        migrations.AddField(
            model_name='tag',
            name='weekly_count',
            field=models.PositiveIntegerField(default=0, verbose_name='осы аптада'),
        ),
    ]
