# Generated by Django 6.0.5 on 2026-09-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_publish_existing_chapters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('NotPublished', 'NotPublished'), ('NeedsWork', 'NeedsWork'), ('OnProcess', 'OnProcess'), ('Completed', 'Completed'), ('OnModeration', 'OnModeration')], default='NotPublished', max_length=16, verbose_name='мәртебесі'),
        ),
    ]
