# Generated by Django 6.0.5 on 2026-09-05 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_needs_work_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True, verbose_name='алынған')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='модератор')),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim', to='core.story', verbose_name='шығарма')),
            ],
            options={
                'verbose_name': 'қаралуда',
                'verbose_name_plural': 'қаралуда',
            },
        ),
        migrations.CreateModel(
            name='ModerationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('approved', 'Жарияланды'), ('needs_work', 'Толықтыру қажет'), ('rejected', 'Қабылданбады')], max_length=16, verbose_name='нәтижесі')),
                ('reason', models.TextField(blank=True, verbose_name='себебі')),
                ('chapters', models.PositiveSmallIntegerField(default=0, verbose_name='бөлім саны')),
                ('decided_at', models.DateTimeField(auto_now_add=True, verbose_name='шешілген')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='модератор')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_decisions', to='core.story', verbose_name='шығарма')),
            ],
            options={
                'verbose_name': 'модерация шешімі',
                'verbose_name_plural': 'модерация шешімдері',
                'ordering': ('-decided_at', '-pk'),
                'indexes': [models.Index(fields=['story', '-decided_at'], name='core_modera_story_i_7ea259_idx')],
            },
        ),
    ]
