# Generated by Django 6.0.5 on 2026-09-06 14:25

from django.db import migrations, models
from django.db.models import F


def _backfill_position(apps, schema_editor):
    """Порядок до этой миграции и был номером — переносим как есть
    ."""
    Chapter = apps.get_model('core', 'Chapter')
    Chapter.objects.update(position=F('number'))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_moderation_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('position', 'number'), 'verbose_name': 'бөлім', 'verbose_name_plural': 'бөлімдер'},
        ),
        migrations.AddField(
            model_name='chapter',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='реті'),
        ),
        migrations.RunPython(_backfill_position, migrations.RunPython.noop),
    ]
