# Generated by Django 6.0.5 on 2026-08-26 05:50

import django.contrib.postgres.indexes
"""Триграммные индексы под поиск по каталогу.

Поиск ищет подстроку — `ILIKE '%жағалау%'` по названию работы и по трём
именам автора сразу. Такой предикат не берёт ни один B-tree: подстрока
начинается не с начала строки, и Postgres читает таблицу целиком. На
двадцати трёх работах это незаметно.

`pg_trgm` индексирует триграммы и потому берёт подстроку с любой
позиции; регистр он складывает сам, так что «РЫСҚАЛИ» и «рысқали» идут
одним путём — ровно то свойство, ради которого проект выбрал Postgres, а
не SQLite (её `LIKE` складывает регистр только для ASCII).

**Полнотекстового поиска здесь намеренно нет.** `SearchVector` + GIN был
бы быстрее, но он ищет словами, а не подстрокой: «Жағал» перестало бы
находить «Жағалау», и это смена поведения продукта, а не оптимизация.
Отдельным решением — когда будет на чём проверить, чего ждёт читатель.

Расширение `pg_trgm` доверенное с Postgres 13, поэтому создаётся ролью
приложения и суперпользователя не требует.
"""

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0008_query_indexes'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='story',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='story_title_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['pen_name'], name='user_pen_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['username'], name='user_username_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='user_name_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
