# Generated by Django 6.0.5 on 2026-09-06 17:50

import core.models
import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chapter_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='poster',
            field=models.FileField(blank=True, max_length=200, upload_to=core.models.contest_poster_path, validators=[core.uploads.validate_raster_image], verbose_name='афиша'),
        ),
        migrations.AlterField(
            model_name='contestaward',
            name='image',
            field=models.FileField(blank=True, max_length=200, upload_to=core.models.award_image_path, validators=[core.uploads.validate_raster_image], verbose_name='эмблема'),
        ),
        migrations.AlterField(
            model_name='story',
            name='cover',
            field=models.FileField(blank=True, max_length=200, upload_to=core.models.story_cover_path, validators=[core.uploads.validate_raster_image], verbose_name='мұқаба'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, max_length=200, upload_to=core.models.user_avatar_path, validators=[core.uploads.validate_raster_image], verbose_name='аватар'),
        ),
    ]
