# Generated by Django 6.0.5 on 2026-08-27 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_story_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='басылған')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_set', to='core.storycomment', verbose_name='пікір')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='оқырман')),
            ],
            options={
                'verbose_name': 'пікір ұнатуы',
                'verbose_name_plural': 'пікір ұнатулары',
                'constraints': [models.UniqueConstraint(fields=('user', 'comment'), name='unique_like_per_user_per_comment')],
            },
        ),
    ]
