# Generated by Django 6.0.5 on 2026-09-08 09:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_telegram_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Спам / жарнама'), ('copy', 'Плагиат / көшірме'), ('offensive', 'Жараспайтын мазмұн'), ('other', 'Басқа')], max_length=16, verbose_name='себебі')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='түсініктеме')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='жіберілген')),
                ('outcome', models.CharField(blank=True, choices=[('dismissed', 'Бұзушылық жоқ'), ('upheld', 'Расталды')], max_length=16, verbose_name='нәтижесі')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='қаралған')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='core.storycomment', verbose_name='пікір')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL, verbose_name='кімнен')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='қараған')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.story', verbose_name='шығарма')),
            ],
            options={
                'verbose_name': 'шағым',
                'verbose_name_plural': 'шағымдар',
                'ordering': ('created_at',),
            },
        ),
    ]
