# Generated by Django 6.0.5 on 2026-08-27 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_comment_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterReactionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('kuldim', 'Күлдім'), ('jyladym', 'Жыладым'), ('juregim', 'Жүрегім'), ('shabyt', 'Шабыт'), ('tangaldym', 'Таңғалдым')], max_length=16, verbose_name='реакция')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='басылған')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_votes', to='core.chapter', verbose_name='бөлім')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_reaction_votes', to=settings.AUTH_USER_MODEL, verbose_name='оқырман')),
            ],
            options={
                'verbose_name': 'бөлім реакциясының дауысы',
                'verbose_name_plural': 'бөлім реакцияларының дауыстары',
                'constraints': [models.UniqueConstraint(fields=('user', 'chapter'), name='one_reaction_per_user_per_chapter')],
            },
        ),
    ]
