# Generated by Django 6.0.5 on 2026-09-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_report'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='user_name_trgm',
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='туған күні'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
