# Generated by Django 6.0.5 on 2026-08-27 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_chapter_reaction_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дауыс берген')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_set', to='core.polloption', verbose_name='нұсқа')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_set', to='core.chapterpoll', verbose_name='сауалнама')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL, verbose_name='оқырман')),
            ],
            options={
                'verbose_name': 'сауалнама дауысы',
                'verbose_name_plural': 'сауалнама дауыстары',
                'constraints': [models.UniqueConstraint(fields=('user', 'poll'), name='one_vote_per_user_per_poll')],
            },
        ),
    ]
