# Generated by Django 6.0.5 on 2026-08-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_poll_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='age_confirmed',
            field=models.BooleanField(default=False, verbose_name='жасын растады'),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_declaration',
            field=models.CharField(choices=[('no', 'no'), ('partial', 'partial'), ('yes', 'yes')], default='no', max_length=8, verbose_name='AI көмегі'),
        ),
        migrations.AddField(
            model_name='submission',
            name='rules_confirmed',
            field=models.BooleanField(default=False, verbose_name='ережені растады'),
        ),
    ]
