# Generated by Django 6.0.5 on 2026-09-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_telegram_push'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='push_moderation',
            field=models.BooleanField(default=True, verbose_name='модерация мен байқау'),
        ),
        migrations.AddField(
            model_name='user',
            name='push_new_chapter',
            field=models.BooleanField(default=True, verbose_name='жаңа бөлімдер'),
        ),
        migrations.AddField(
            model_name='user',
            name='push_response',
            field=models.BooleanField(default=True, verbose_name='оқырман жауабы'),
        ),
    ]
