# Generated by Django 6.0.5 on 2026-08-27 10:43

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_submission_declarations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='жасы'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, max_length=200, upload_to=core.models.user_avatar_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'], message='Тек растр сурет: png, jpg, webp. SVG қабылданбайды (BR-46).')], verbose_name='аватар'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('boy', 'Ұл'), ('girl', 'Қыз')], max_length=4, verbose_name='жынысы'),
        ),
    ]
