# Generated by Django 6.0.5 on 2026-09-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_push_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('comment', 'comment'), ('like', 'like'), ('new_chapter', 'new_chapter'), ('follower', 'follower'), ('moderation', 'moderation'), ('contest', 'contest'), ('tag', 'tag')], max_length=16, verbose_name='түрі'),
        ),
    ]
