# Generated by Django 6.0.5 on 2026-09-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_notification_tag_kind'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True), ('story__isnull', False)), fields=('reporter', 'story'), name='one_open_report_per_story_per_reporter'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('comment__isnull', False), ('resolved_at__isnull', True)), fields=('reporter', 'comment'), name='one_open_report_per_comment_per_reporter'),
        ),
    ]
