"""Счётчики тега перестают храниться (PLAN-OPTIMIZATION, шаг 1.10, DEC-53).

`usage_count` был вычислим и без этого, а `weekly_count` — нет: когда тег
появился на работе, нигде не записывалось, и он лежал литералом, который
не менялся никогда. Витрина «Осы аптада» (DEC-31) держится ровно на
расхождении с накопленной — с замершим числом она вырождалась в её копию.

Дата в связке появилась в Ф15 (`StoryTag.created_at`), и оба счёта теперь
считаются по ней. Данные не переносятся: числа корпуса (42, 56, 31)
никаким связкам не соответствовали.

Индексы под сортировку по этим колонкам уходят вместе с ними — порядок
задают агрегаты, и колоночного индекса под него быть не может.
"""

# Generated by Django 6.0.5 on 2026-08-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_libraryentry_progress_chapter'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tag',
            name='core_tag_status_f71c54_idx',
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='core_tag_status_617cf5_idx',
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['status'], name='core_tag_status_6e19bd_idx'),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='usage_count',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='weekly_count',
        ),
    ]
