# Generated by Django 6.0.5 on 2026-09-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_drop_age_and_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedtagpattern',
            name='scope',
            field=models.CharField(choices=[('tag', 'тег атауы'), ('comment', 'пікір мәтіні'), ('both', 'екеуі де')], default='tag', max_length=8, verbose_name='қайда қолданылады'),
        ),
        migrations.AddField(
            model_name='storycomment',
            name='held',
            field=models.BooleanField(default=False, verbose_name='тексеруде'),
        ),
    ]
