"""Счётчики тега перестают храниться (PLAN-OPTIMIZATION, шаг 1.10, DEC-53).

Оба считаются по `StoryTag.created_at`. Данные не переносятся: числа
корпуса никаким связкам не соответствовали. Индексы под сортировку уходят
вместе с колонками — порядок задают агрегаты, и колоночного индекса под
него быть не может.
"""

# Generated by Django 6.0.5 on 2026-08-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_libraryentry_progress_chapter'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tag',
            name='core_tag_status_f71c54_idx',
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='core_tag_status_617cf5_idx',
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['status'], name='core_tag_status_6e19bd_idx'),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='usage_count',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='weekly_count',
        ),
    ]
