# Generated by Django 6.0.5 on 2026-09-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_held_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True, verbose_name='күні')),
                ('signed_up', models.PositiveIntegerField(default=0, verbose_name='кірді')),
                ('onboarded', models.PositiveIntegerField(default=0, verbose_name='анкетаны аяқтады')),
                ('wrote', models.PositiveIntegerField(default=0, verbose_name='жаза бастады')),
                ('published', models.PositiveIntegerField(default=0, verbose_name='жариялады')),
                ('drafts', models.PositiveIntegerField(default=0, verbose_name='жоба')),
                ('public', models.PositiveIntegerField(default=0, verbose_name='жарияланған')),
                ('decided_week', models.PositiveIntegerField(default=0, verbose_name='аптада шешілді')),
                ('returned_week', models.PositiveIntegerField(default=0, verbose_name='аптада қайтарылды')),
                ('overdue', models.PositiveIntegerField(default=0, verbose_name='мерзімнен асқан')),
                ('readers', models.PositiveIntegerField(default=0, verbose_name='оқыған')),
                ('returning_readers', models.PositiveIntegerField(default=0, verbose_name='кеше де оқыған')),
            ],
            options={
                'verbose_name': 'портал күні',
                'verbose_name_plural': 'портал күндері',
                'ordering': ('-day',),
                'get_latest_by': 'day',
            },
        ),
    ]
