# Generated by Django 6.0.5 on 2026-08-29 06:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_tag_counts_derived'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='оқылған сәт')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_set', to='core.story', verbose_name='шығарма')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='оқырман')),
            ],
            options={
                'verbose_name': 'оқылым',
                'verbose_name_plural': 'оқылымдар',
                'indexes': [models.Index(fields=['story', '-created_at'], name='core_storyv_story_i_870e74_idx'), models.Index(fields=['created_at'], name='core_storyv_created_70219a_idx')],
            },
        ),
    ]
