# Generated by Django 6.0.5 on 2026-09-22 09:29

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_portal_day'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='story',
            index=django.contrib.postgres.indexes.GinIndex(fields=['annotation'], name='story_annotation_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
