"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Секреты и адрес БД — из `.env` (в .gitignore). Образец — `.env.example`.
# Файла может не быть: в CI и в проде те же переменные приходят из окружения.
load_dotenv(BASE_DIR / '.env')


# ── Режим: одна переменная, а не набор совпадений ────────────────────────
#
# `DJANGO_ENV=production` — единственный переключатель. Раньше прод
# отличался от разработки тремя независимыми переменными, и любая забытая
# давала «почти прод»: `DEBUG=1` раздавал трейсбэки, пустой `SECRET_KEY`
# молча подставлял ключ из репозитория, пустой `ALLOWED_HOSTS` ронял
# первый же запрос.
#
# Дефолт — разработка, и это осознанно. Забытая переменная должна давать
# **безопасно неработающий** прод, а не незаметно работающий: ниже стоят
# три проверки, каждая из которых валит запуск, а не подменяет значение.
DJANGO_ENV = os.environ.get('DJANGO_ENV', 'dev')
PRODUCTION = DJANGO_ENV == 'production'

# `DEBUG` читается отдельно: под тестами Django выставляет его в `False`
# уже после импорта, и разработке нужен `True` без лишней переменной.
DEBUG = os.environ.get('DJANGO_DEBUG', '0' if PRODUCTION else '1') == '1'

if PRODUCTION and DEBUG:
    raise ImproperlyConfigured(
        'DJANGO_ENV=production вместе с DJANGO_DEBUG=1: прод с трейсбэками '
        'на странице — не прод. Убери DJANGO_DEBUG.'
    )

# SECURITY WARNING: keep the secret key used in production secret!
#
# В проде ключ обязателен и падает громко — как `DATABASE_URL` строкой
# ниже. Дефолт из репозитория подписывал бы сессии и CSRF ключом, который
# лежит в открытом доступе, и заметить это было бы нечем.
SECRET_KEY = os.environ.get('SECRET_KEY', '')
if not SECRET_KEY:
    if PRODUCTION:
        raise ImproperlyConfigured(
            'Не задан SECRET_KEY. В проде он обязателен: им подписываются '
            'сессии и CSRF-токены.'
        )
    SECRET_KEY = 'django-insecure-wa*es)k#sjqb-j=bl70+0#p_1bm9t0x%sp2s6_hou2wr$!*^6y'

ALLOWED_HOSTS = [h for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h]
# Не про прод: DJANGO_ALLOWED_HOSTS задан и локально, когда за адресом
# стоит туннель (ngrok/cloudflared) — тогда прокси-доверие ниже нужно и
# в dev, см. `_hosts_explicit`.
_hosts_explicit = bool(ALLOWED_HOSTS)
if PRODUCTION and not ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        'Не задан DJANGO_ALLOWED_HOSTS. Пустой список в проде означает, что '
        'ни один запрос не пройдёт, — лучше узнать об этом при запуске.'
    )
if not ALLOWED_HOSTS:
    # Разработка: `runserver` и тестовый клиент. При `DEBUG=True` Django
    # подставляет первые три сам, но `testserver` — только под раннером,
    # и разовый скрипт с `django.test.Client` об этом спотыкался.
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]', 'testserver']


# ── Telegram Login Widget (NFR-25) ────────────────────────────────────────
#
# Токен подписывает проверку личности — обязателен в проде, как SECRET_KEY
# выше. В dev/тестах бот не зарегистрирован: подпись всё равно считается
# этим же токеном и внутри теста, и в `verify_telegram_auth`, поэтому
# плейсхолдер работает без внешнего бота. `BOT_USERNAME` только для
# рендера кнопки — пустой в dev просто не рисует виджет.
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '')
if not TELEGRAM_BOT_TOKEN:
    if PRODUCTION:
        raise ImproperlyConfigured(
            'Не задан TELEGRAM_BOT_TOKEN. В проде им проверяется подпись '
            'Telegram Login Widget — без него любой вход неотличим от '
            'подделанного.'
        )
    TELEGRAM_BOT_TOKEN = 'dev-insecure-telegram-bot-token'

TELEGRAM_BOT_USERNAME = os.environ.get('TELEGRAM_BOT_USERNAME', '')
if PRODUCTION and not TELEGRAM_BOT_USERNAME:
    raise ImproperlyConfigured(
        'Не задан TELEGRAM_BOT_USERNAME. Без него виджету некуда слать '
        'запрос авторизации.'
    )

# Django 4+ по умолчанию ставит `Cross-Origin-Opener-Policy: same-origin` —
# это рвёт `window.opener` у попапа, который открывает сам Telegram Login
# Widget в redirect-режиме: подтвердив вход, попап не может перенаправить
# окно-родитель на наш callback и просто закрывается. `-allow-popups`
# сохраняет изоляцию от чужих окон, но не от тех, что открыла сама страница.
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Ради `GinIndex` с `gin_trgm_ops` и операции `TrigramExtension` в
    # миграции 0009: поиск по каталогу — это `ILIKE '%…%'`, и без
    # триграммного индекса он читает таблицу целиком.
    'django.contrib.postgres',
    'django.contrib.sitemaps',
    'core'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.OnboardingGuardMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

# Своя модель пользователя заводится до первой миграции `core` и позже не
# меняется без пересоздания базы. Отдельной модели «автор» нет: читателя как
# роли не существует (DEC-01), любой зарегистрированный сразу и пишет.
AUTH_USER_MODEL = 'core.User'

# Куда Django отправляет за входом (`login_required`, админка при отказе).
# Дефолт `/accounts/login/` в проекте не существует, и отказ уводил бы на 404.
LOGIN_URL = 'core:login'
LOGIN_REDIRECT_URL = 'core:home'
LOGOUT_REDIRECT_URL = 'core:home'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.auth_state',
                'core.context_processors.nav_state',
                'core.context_processors.site_links',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# PostgreSQL, а не SQLite: у SQLite `LIKE` складывает регистр только для ASCII,
# и поиск по каталогу («Рысқали», «Жағалау») вёл бы себя не так, как поиск в
# Python. Для казахоязычного портала это не деталь деплоя, а поведение продукта.
# Одной строкой подключения — чтобы прод отличался от локали только значением
# переменной, а не веткой в коде.

DATABASE_URL = os.environ.get('DATABASE_URL')
if not DATABASE_URL:
    raise ImproperlyConfigured(
        'Не задан DATABASE_URL. Скопируй `.env.example` в `.env` '
        'и укажи строку подключения к Postgres.'
    )

DATABASES = {
    'default': dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,        # переиспользуем соединение: у Postgres коннект дорогой
        conn_health_checks=True,  # но проверяем живость, иначе ловим порванный сокет
    ),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'kk'

TIME_ZONE = 'Asia/Almaty'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Куда `collectstatic` складывает собранное. Без этой строки команда
# отказывается работать вовсе, и обнаруживалось бы это в день деплоя:
# gunicorn отдал бы страницы без единого стиля.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user-uploaded; в стабе — placeholder обложки)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Вторая линия защиты рядом с `core.uploads.validate_raster_image`
# (BR-86, S8 в AUDIT-WRITE-FLOW.md): оба порога — про буферизацию/тело
# запроса на уровне Django, а не про конкретное поле, но раньше не были
# заданы вовсе. Число — то же, что `core.uploads.RASTER_MAX_BYTES`;
# не импортируется оттуда, чтобы настройки не тянули код приложения.
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Cache
#
# Кэшируются **редакционные справочники**, а не выдача: жанры со
# счётчиками, ссылки «Авторлар мектебі» и индекс Cmd+K. Все три меняются
# раз в месяц, а спрашиваются на каждой странице — ссылки школы отдаёт
# глобальный контекст-процессор.
#
# Бэкенд локальный, то есть **свой у каждого процесса**. Для справочников
# с коротким TTL это приемлемо: расхождение между воркерами живёт минуты и
# касается списка ссылок в подвале. Как только понадобится кэшировать
# что-то, где расхождение видно пользователю, сюда встанет Redis — и
# менять придётся только эти пять строк.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'qazaqnovel',
        'TIMEOUT': 300,
    },
}


# Logging
#
# Без этого блока `logger.warning` из `views/auth.py` уходил в никуда:
# у Django есть дефолтная конфигурация, но она показывает записи только
# при `DEBUG=True`. Единственное предупреждение проекта — «демо-аккаунта
# нет в базе» — сообщает ровно о том, из-за чего не работает вход.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'plain': {'format': '{asctime} {levelname} {name}: {message}',
                  'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'plain'},
    },
    'root': {'handlers': ['console'], 'level': 'INFO'},
    'loggers': {
        'django.request': {'handlers': ['console'], 'level': 'WARNING',
                           'propagate': False},
    },
}


# ── Прод и прокси-туннель ─────────────────────────────────────────────────
#
# Ничего — под `DEBUG`. Разница принципиальная: тестовый раннер выставляет
# `DEBUG = False` уже после импорта настроек, и блок «если не DEBUG»
# включил бы в тестах редирект на https, то есть уронил бы суиту целиком.
# `PRODUCTION` читается из окружения и под тестами остаётся ложным.
# Прокси-доверие (`_hosts_explicit`) — не только прод: та же проблема у
# локального туннеля (ngrok/cloudflared) с явным `DJANGO_ALLOWED_HOSTS`.
if _hosts_explicit:
    # За прокси (прод — за настоящим, dev — за ngrok/cloudflared-туннелем)
    # Django узнаёт про https только из заголовка; без этой пары Origin у
    # POST выглядит http-адресом и падает проверкой CSRF, а
    # `SECURE_SSL_REDIRECT` в проде без неё уводит в бесконечный редирект.
    # Домены — те же, что уже разрешены ALLOWED_HOSTS: новой поверхности
    # доверие не открывает.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    CSRF_TRUSTED_ORIGINS = [f'https://{h}' for h in ALLOWED_HOSTS]

if PRODUCTION:
    SECURE_SSL_REDIRECT = True
    # Год и поддомены — рекомендация Django; включать HSTS постепенно
    # (60 → 3600 → год) имеет смысл на живом домене, до запуска незачем.
    SECURE_HSTS_SECONDS = 31_536_000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Статику отдаёт whitenoise, если он установлен (группа `prod`).
    # Хранилище **без манифеста**: манифестное требует, чтобы каждый файл,
    # упомянутый в `{% static %}`, лежал в `STATIC_ROOT`, и падает на
    # рендере, если `collectstatic` не прошёл. Отдавать страницу без
    # одного шрифта лучше, чем не отдавать вовсе.
    try:
        import whitenoise  # noqa: F401
    except ImportError:
        pass
    else:
        MIDDLEWARE.insert(
            MIDDLEWARE.index('django.middleware.security.SecurityMiddleware') + 1,
            'whitenoise.middleware.WhiteNoiseMiddleware')
        STORAGES = {
            'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
            'staticfiles': {
                'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
        }

# Демо-корпус кладётся в тестовую базу один раз за прогон, сразу после
# миграций: страницы читают базу, и корпус нужен почти каждому тесту.
# Подробности и цена решения — в `core/tests/runner.py`.
TEST_RUNNER = 'core.tests.runner.SeededTestRunner'

# ── django-debug-toolbar: только в разработке ────────────────────────────
# Пакет лежал в зависимостях и не был подключён никуда. Подключён он стоит
# больше, чем удалён: панель SQL показывает число запросов и сам их текст
# на живой странице — то, ради чего иначе пишется разовый скрипт с
# `CaptureQueriesContext`. Ровно этим и нашлись 59 запросов на своём
# профиле.
#
# Под тестами панели нет и без флага: Django выставляет `DEBUG = False`.
# `DEBUG_TOOLBAR=0` нужен для другого — выключить её в разработке, когда
# она мешает (снимок вёрстки, замер времени ответа), не трогая `DEBUG`.
if DEBUG and os.environ.get('DEBUG_TOOLBAR', '1') == '1':
    try:
        import debug_toolbar  # noqa: F401
    except ImportError:
        # Группа `dev` не установлена — это нормально в проде и в CI.
        pass
    else:
        INSTALLED_APPS.append('debug_toolbar')
        # Перед CommonMiddleware, как требует документация пакета.
        MIDDLEWARE.insert(
            MIDDLEWARE.index('django.middleware.common.CommonMiddleware'),
            'debug_toolbar.middleware.DebugToolbarMiddleware')
        # Показывать не по IP, а по DEBUG: адрес разработки бывает не
        # localhost (WSL, docker, телефон в той же сети), и дефолтная
        # проверка `INTERNAL_IPS` молча прячет панель.
        #
        # `DEBUG` читается **в момент запроса**, а не здесь. Тестовый раннер
        # выставляет его в `False` уже после импорта настроек, поэтому
        # константа `True` оставила бы панель включённой под тестами: её
        # middleware оборачивает курсор и ходит в базу само, и бюджет
        # запросов вырос на треть — страница при этом ничего не меняла.
        def _show_toolbar(request):
            from django.conf import settings as live

            return live.DEBUG

        DEBUG_TOOLBAR_CONFIG = {'SHOW_TOOLBAR_CALLBACK': _show_toolbar}
